CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "UserName" text NOT NULL,
    "Email" text NOT NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "Posts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "PublishedAt" timestamp with time zone,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "AuthorId" text,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id")
);


CREATE TABLE "Comments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Content" text NOT NULL,
    "AuthorId" text NOT NULL,
    "PostId" bigint NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Comments_AuthorId" ON "Comments" ("AuthorId");


CREATE INDEX "IX_Comments_PostId" ON "Comments" ("PostId");


CREATE INDEX "IX_Posts_AuthorId" ON "Posts" ("AuthorId");


